In [2]:
import sys # esto sirve para mostrar el output completo de una lista larga 


import numpy as np
import pandas as pd 
import networkx as nx
import math
import sympy as sp
import matplotlib.pyplot as plt
import gc
import time

np.set_printoptions(threshold=sys.maxsize) # esto sirve para mostrar el output completo de una lista larga 


from sympy import *
from numpy import linalg as LA
from numpy.linalg import matrix_rank

In [16]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactive="all"

In [20]:
pd.options.display.max_rows = 4000

In [2]:
#Establecer directorio de datos

DIR='/Users/I_am_AlexX/Downloads/Telegram Desktop'
FILE='/adjmatrix_UNT.txt'

file='{}{}'.format(DIR,FILE)

print('File directory:{}'.format(file))

File directory:/Users/I_am_AlexX/Downloads/Telegram Desktop/adjmatrix_UNT.txt


In [4]:
data=pd.read_table(file)

NameError: name 'file' is not defined

In [3]:
a=np.diag(np.ones(16748),0)
A=data-a

NameError: name 'data' is not defined

In [5]:
del a

In [6]:
del data

In [7]:
#Se obtiene el mismo resultado 

threshold= A.mean().mean()
threshold

0.033064517362779086

In [8]:
#Función para ver qué forma tiene la matriz del data set que estamos
#estudiando 

def mat_shape(mat,n):
    
    new_data=mat.iloc[:n,:n]
    
    new_data2=new_data.apply(lambda x:(np.where(x<threshold,0,x)))
    adj_mat=new_data2.apply(lambda x:(np.where(x>threshold,1,x)))
    
    #completar la matriz triangular superior para tener la forma completa de una matriz
    # simétrica
    
    adj_mod=np.matrix(adj_mat.fillna(0))
    adj_mod_trans=adj_mod.transpose()
    simm_mat=adj_mod+adj_mod_trans
    
    
    return simm_mat

In [9]:
#Función para contruir la matriz de grado a partir de la de la matriz de adyacencia

def degree_mat_from_adj(mat,n):
    
    simm_mat = mat_shape(mat, n)
     
    Adj_to_nx=nx.from_numpy_matrix(simm_mat)
    
    L_from_Adj=nx.laplacian_matrix(Adj_to_nx) #obtener la Laplaciana asociada a la de adyacencia
    L_arr=L_from_Adj.toarray()
    L_np=np.matrix(L_arr)
    
    deg_Mat=L_np+simm_mat
    
    return deg_Mat

In [10]:
#La siguiente función sirve para obtener los elementos de la diagonal de la matriz de
# grado y la guarda en un array llamado out_p


def get_elem_in_diag(Mat):
    Mat_mod = np.squeeze(np.asarray(Mat))#convierte numpy matrix en array
    out_p=[]
    for elem in np.nditer(Mat_mod): #nditer itera sobre arrays
        if elem != 0: # omite los valores 0 en el array pues la matriz de grado fuera de la diagonal tiene solo ceros
            out_p.append(int(elem))
            
    return out_p

In [11]:
# El siguiente módulo, crea un array con los primeros "n" genes que deseen obtener del
# Data Frame "data"

#Parametros: data , n 

def get_genes(data,n):
    
    genes_arr = sorted(data) #obtener un array que contiene los elementos del header del DataFrame
    num_genes_extracted = range(n)
    genes = np.array(genes_arr)[num_genes_extracted]
    
    return genes

In [12]:
#Este script es capaz de dibujar el grafo con sus vértices respectivos etiquetados

#Este módulo ha sifo modificado para que sea capaz de etiquetar los nombres de los genes 
#involucrados

def plt_with_label(mat,n):
    
    simm_mat = mat_shape(mat, n)
    
    adj_to_graph=nx.from_numpy_matrix(simm_mat)
    labelmap=dict(zip(adj_to_graph.nodes(),get_genes(data,n)))
    
    plt.figure(1,figsize=(20,20))
    
    nx.draw(adj_to_graph, labels=labelmap, with_labels=True,
    font_size=15,font_weight='bold',font_color='black',edge_color='gray',node_color='green',node_size=200)
    
    graph_with_lab=plt.show()
    
    return graph_with_lab

In [13]:
#Función para obtener los números de mayor a menor de una lista

def func(a,N):
    return np.argsort(a)[::-1][:N]

In [14]:
plt_with_label(A,45)

NameError: name 'data' is not defined

In [15]:
mat_shape(A,5).dot(get_elem_in_diag( degree_mat_from_adj(A,5)))

matrix([[6., 9., 9., 8., 8.]])

In [100]:
type(mat_shape(A,5).dot(get_elem_in_diag( degree_mat_from_adj(A,5))))

numpy.matrix

In [102]:
M5= np.squeeze(np.asarray(mat_shape(A,5).dot(get_elem_in_diag( degree_mat_from_adj(A,5)))))
M5

array([6., 9., 9., 8., 8.])

In [103]:
func(M5,5)

array([2, 1, 4, 3, 0], dtype=int64)

In [14]:
M45=mat_shape(A,45).dot(get_elem_in_diag( degree_mat_from_adj(A,45)))

In [15]:
M45

matrix([[451., 338., 255., 483., 423., 230., 438., 377., 341., 412.,
         489., 411., 417., 325., 461., 385., 358., 491., 409., 331.,
         424., 363., 474., 369., 533., 309., 277., 456., 472., 420.,
         345., 460., 453., 384., 438., 180., 466., 461., 337., 424.,
         328., 430., 458., 310., 498.]])

In [16]:
np.asarray(M45)

array([[451., 338., 255., 483., 423., 230., 438., 377., 341., 412., 489.,
        411., 417., 325., 461., 385., 358., 491., 409., 331., 424., 363.,
        474., 369., 533., 309., 277., 456., 472., 420., 345., 460., 453.,
        384., 438., 180., 466., 461., 337., 424., 328., 430., 458., 310.,
        498.]])

In [17]:
type(M45)

numpy.matrix

In [18]:
type(np.asarray(M45))

numpy.ndarray

In [19]:
np.squeeze(np.asarray(M45))

array([451., 338., 255., 483., 423., 230., 438., 377., 341., 412., 489.,
       411., 417., 325., 461., 385., 358., 491., 409., 331., 424., 363.,
       474., 369., 533., 309., 277., 456., 472., 420., 345., 460., 453.,
       384., 438., 180., 466., 461., 337., 424., 328., 430., 458., 310.,
       498.])

In [20]:
type(np.squeeze(np.asarray(M45)))

numpy.ndarray

In [24]:
M45_2=np.squeeze(np.asarray(M45))

In [110]:
func(M45_2,45)

array([24, 44, 17, 10,  3, 22, 28, 36, 14, 37, 31, 42, 27, 32,  0, 34,  6,
       41, 39, 20,  4, 29, 12,  9, 11, 18, 15, 33,  7, 23, 21, 16, 30,  8,
        1, 38, 19, 40, 13, 43, 25, 26,  2,  5, 35], dtype=int64)

In [112]:
get_genes(A,45)[24]

'ENSG00000003056'

In [113]:
get_genes(A,45)[44]

'ENSG00000004534'

In [114]:
get_genes(A,45)[17]

'ENSG00000002549'

In [119]:
get_genes(A,45)[10]

'ENSG00000001561'

In [120]:
get_genes(A,45)[3]

'ENSG00000000460'

In [121]:
func(get_elem_in_diag(degree_mat_from_adj(A,45)),45) 

array([24, 44,  3, 10, 31, 28, 14, 17, 27, 22, 36, 42, 39,  4, 37,  0, 32,
       34,  6, 41, 20, 11, 12, 18, 29,  9, 23, 33,  7, 15, 21, 38,  8, 19,
       30, 16, 43, 13,  1, 40, 25, 26,  2,  5, 35], dtype=int64)

In [122]:
func(M45_2,45)

array([24, 44, 17, 10,  3, 22, 28, 36, 14, 37, 31, 42, 27, 32,  0, 34,  6,
       41, 39, 20,  4, 29, 12,  9, 11, 18, 15, 33,  7, 23, 21, 16, 30,  8,
        1, 38, 19, 40, 13, 43, 25, 26,  2,  5, 35], dtype=int64)

In [26]:
func(M45,45)

matrix([[35,  5,  2, 26, 25, 43, 13, 40, 19, 38,  1,  8, 30, 16, 21, 23,
          7, 33, 15, 18, 11,  9, 12, 29,  4, 20, 39, 41,  6, 34,  0, 32,
         27, 42, 31, 37, 14, 36, 28, 22,  3, 10, 17, 44, 24]], dtype=int64)

In [27]:
M45

matrix([[451., 338., 255., 483., 423., 230., 438., 377., 341., 412.,
         489., 411., 417., 325., 461., 385., 358., 491., 409., 331.,
         424., 363., 474., 369., 533., 309., 277., 456., 472., 420.,
         345., 460., 453., 384., 438., 180., 466., 461., 337., 424.,
         328., 430., 458., 310., 498.]])

In [28]:
M45_2

array([451., 338., 255., 483., 423., 230., 438., 377., 341., 412., 489.,
       411., 417., 325., 461., 385., 358., 491., 409., 331., 424., 363.,
       474., 369., 533., 309., 277., 456., 472., 420., 345., 460., 453.,
       384., 438., 180., 466., 461., 337., 424., 328., 430., 458., 310.,
       498.])

In [ ]:
#Análisis de matrices grandes 

# Análisis de centralidad de vector propio en  matrices grandes 

In [29]:
M_1000=mat_shape(A,1000).dot(get_elem_in_diag( degree_mat_from_adj(A,1000)))

In [30]:
M_1000_2=np.squeeze(np.asarray(M_1000))

In [31]:
func(get_elem_in_diag(degree_mat_from_adj(A,1000)),1000) 

array([465, 221, 555, 365, 732, 373, 346, 514,  66, 166, 557, 358, 251,
       214, 649, 894, 317,  41, 811, 375, 918, 263, 640, 806, 153, 619,
        31, 565, 297, 127,  43, 520, 728, 241, 690, 747, 371, 398,  47,
       820, 316, 197,  94, 652, 156,  61, 455, 788, 123, 171, 161, 710,
        79, 763, 571, 289, 198, 586, 258, 863, 424, 639, 752, 205, 545,
       415, 892, 641,   3, 165, 441, 862, 479, 868, 132, 593, 861, 549,
       734, 389, 716, 803, 874, 799, 204, 845,  74, 217, 357, 667, 147,
        29, 815, 929, 839, 329, 943, 920, 288,  83, 150, 661, 588,  75,
       886, 883, 805, 272, 416, 426, 663, 534, 470, 266, 719, 891, 481,
       843, 847,  53, 781, 162, 852, 896, 574, 611, 249, 818, 561, 253,
         0, 889, 160, 438, 991, 973, 448, 286,  82, 701, 237, 628, 854,
       875, 392, 767, 445, 882,  24,  48, 633, 212, 718, 686, 469, 798,
       341, 990, 695, 927, 254,  71, 459, 961, 271, 944, 169, 864, 804,
       427, 853, 616,  12, 617, 490, 282, 758, 179, 871, 432, 13

In [32]:
func(M_1000_2,1000)

array([465, 221, 555, 365, 732, 346,  66, 251, 373, 649, 214, 358, 166,
       514, 557, 894, 317,  41, 918, 640, 263, 375, 806, 811, 619, 153,
        31, 565,  43, 297, 127, 520, 241, 690, 728,  61, 371, 398, 820,
       316, 747,  47, 156, 197, 652, 710,  94, 123, 788, 455, 161, 763,
       289, 752, 571,  79, 586, 198, 171, 424, 863, 258, 205, 862, 415,
       892, 165, 641, 639, 734, 441, 132,   3, 545, 389, 868, 716, 593,
       803, 874, 839, 204, 549, 147, 479, 799, 861, 929,  74, 667, 357,
       845, 815, 266, 943, 805,  29, 329, 883, 217, 162, 843, 288, 470,
       150, 561,  83, 920, 272, 886,  75, 588, 481, 663, 891, 847, 416,
       661, 574, 426,  53, 852, 973, 781, 438, 253, 719, 534, 286, 237,
       818, 611, 469, 896, 160, 889, 212, 448, 249, 628, 701,   0, 990,
       254, 854,  24, 961, 686, 718, 445,  48, 695, 798, 882,  82, 875,
       235, 991, 392, 341, 864, 271, 169, 459,  71, 633, 804, 767, 427,
       138, 432,  12, 944, 179, 853, 927, 871, 282, 490, 758, 61

In [25]:
M_2000=mat_shape(A,2000).dot(get_elem_in_diag( degree_mat_from_adj(A,2000)))
M_2000_2=np.squeeze(np.asarray(M_2000))
func(M_2000_2,2000)


array([ 465, 1716,  365, 1540,  358, 1430, 1467, 1299,  166, 1631,   66,
       1855,  251,  221, 1884, 1488,  514,  894,  263,  317,  806,  555,
        214, 1521, 1924, 1342, 1419, 1885,  649,   31,  811, 1741, 1655,
       1128,  415,  732, 1911, 1899, 1302,  316, 1835,  346, 1363,  127,
       1935,  565,  557, 1620,  619, 1284,  918,  805, 1255,  892, 1877,
       1116,  929, 1396,  375, 1629, 1868, 1025, 1913,   43,  852, 1409,
        373, 1248, 1376,  863, 1990, 1839, 1514, 1644, 1170, 1546, 1453,
         61,  123,  156, 1541, 1358,  258,  815, 1852,  728,   41,  197,
       1659, 1186, 1256,  862, 1272,  640, 1079, 1092, 1591,  204, 1000,
       1970, 1875, 1715, 1804,  734, 1907, 1704, 1310,  891, 1225, 1489,
       1674, 1461,  798,  763, 1567,  820, 1131,  165, 1860,  690,  138,
         48,  667, 1737, 1931, 1830,   94,  455,  716,  652,  212, 1725,
        162, 1205,  147,  799,  788, 1031, 1977, 1565,  107, 1431,  586,
        371, 1395,  161, 1999, 1864,  718, 1285, 10

In [34]:
func(get_elem_in_diag(degree_mat_from_adj(A,2000)),2000) 

array([ 465, 1716,  365, ..., 1910, 1847,  414], dtype=int64)

In [26]:
M_3000=mat_shape(A,3000).dot(get_elem_in_diag( degree_mat_from_adj(A,3000)))
M_3000_2=np.squeeze(np.asarray(M_3000))
func(M_3000_2,3000)

array([ 465, 2457, 2005, 1716,  365, 2096, 2285, 1631,  166, 1299, 1467,
       2077, 2032, 2071, 1430,  894,  358, 1540, 1924, 2597, 1128,   66,
        251, 2054,  811, 1884,  514, 1855, 2517, 1521,  214, 1885, 1302,
       1488,  806, 1255,  127,  221,   31, 2504,  263, 2568, 1655,  317,
       1741,  565, 2263, 1911, 1620, 1935,  555,  892,  316, 2838, 2578,
       2453, 1419, 1839, 1835, 1363,  918, 2985, 2124, 2182, 2180, 1342,
       2161,  346,  415, 2370, 1284, 1877, 1025,   61,  891, 2929,  123,
        373, 2847, 1546,  649, 2079,   48,  805,   43, 1868, 1830, 2871,
       1248, 2454, 2282, 1629,  619,  732, 1256, 2034, 2723, 1396,  557,
       2575,  156, 1031, 1395,  197,  863, 2951, 2313, 2031, 1899, 2083,
       2746, 1804, 1170, 1725, 1720, 1409, 1644, 2275, 2754, 2382, 1358,
        852, 2442,  690, 1285, 1453, 2093, 2065, 1567, 1913,  375, 1541,
       1674,  798, 1852, 2718, 1092, 2523,  426, 1376,  640, 1150, 2494,
       2021, 1990,  820, 2044, 1454,  138, 2086, 11

In [37]:
func(get_elem_in_diag(degree_mat_from_adj(A,3000)),3000) 

array([ 465, 2457, 2005, ..., 2112, 2473,  414], dtype=int64)

In [27]:
inicio = time.perf_counter()

M_4000=mat_shape(A,4000).dot(get_elem_in_diag( degree_mat_from_adj(A,4000)))
M_4000_2=np.squeeze(np.asarray(M_4000))
res= func(M_4000_2,4000)

final = time.perf_counter()

print("genes relevantes son",res )
print("el tiempo de corrida fue, ", final- inicio)

genes relevantes son [ 465 3742  365 3766 2457 3866 1540  894 3067 3383 1631 3241 2285 2032
 2096 3976 1467 1716 2005 3692 1299  166 3384 3779 2071  221 1430 3181
  263 1488 2517   66 3719 1128  251 3741 2077 1255  358 3743  514 2504
 2597 1302   31  214 2568 3355  555 1884 3491 1521  811 1655 3975  649
 1924 2263 3755 2985  732 1855  806 1419 2838  316 1885 2054 2871 3379
  619 2370   43 3186 1342  373 3235  565 3923 1835  918 3673 1839 3323
  317 1620  127 1935 2180 2161 1284 3859 1025 1644 1363  156 3460  929
 2578 1256 3348 2124 1674  557 1741 2182  891 3343  415 3622 1629 1376
 3695  123 3815 1911 3723 3857 3458 1514 3819 1546 2929  892 1877 2494
 2282 2275 3342   61 1000 3592 2034 1804 3509 1409 2453  346 3216 3703
 3977 2021 1453 3700 3993 3886 1720 1868 3222 1737 1116 1725  205  728
 3532 1358   48 3357  863 2754  805 1031 3915  426 3551 3764  718  690
 2454  375  197  640 3370 2044 1567 2079 3616 1248  716 1015 3652  852
  162  289 1395 2295 3393   94 2723 1489 2847  297 3557 

In [43]:
inicio = time.perf_counter()

res= func(get_elem_in_diag(degree_mat_from_adj(A,4000)),4000) 

final = time.perf_counter()

print("genes relevantes son",res )
print("el tiempo de corrida fue, ", final- inicio)

genes relevantes son [ 465 3742  365 ...  414 1910 2112]
el tiempo de corrida fue,  44.60284169999977


In [28]:
inicio = time.perf_counter()

M_5000=mat_shape(A,5000).dot(get_elem_in_diag( degree_mat_from_adj(A,5000)))
M_5000_2=np.squeeze(np.asarray(M_5000))
res= func(M_5000_2,5000)

final = time.perf_counter()

print("genes relevantes son",res )
print("el tiempo de corrida fue, ", final- inicio)

genes relevantes son [ 465 3742  365 3766 3866 3241 1540 2457 1631 3383 4617  894 3067 3976
 1716 2032 1299 4625 3692 2071  166 2285 1467 4336 4173   66 2005 2517
  221 2096 4204  263 3779 3384 3181 3719 1430 4709 1255  251  358 4162
   31 4459 1128 2504 4407 2597 3741 4230 4098  555 2077 1488  514 4681
  214 3975 4514 2568  811 4009 4835 3743 1419 1924 4256 2370 4907  619
 1884 4066  732 1655 2180 3755 3491 4721  316 2985 1302   43 4221 3355
 4399  806 1855 1342 1284 4770 1885 4001  565 1409 3379  649 1620 2263
 2871  918 3323 3859 3923 1376 1025 1935 3460 2578 2838  373  127 1521
 1839 1629 1835 3186 3343 3509 4473 2182 4097 3815 4771 2054 3700 2124
 4022  929 3458 1363 1256 2161  317 3673 3993 4243  891  557 3235 4485
  156 1116 1877 3819 1741 3977  718 3592 4429 3723  375 4386 3551 4014
 1644 3310 4639 1674 2034   41 4899 3857 2275 1514 3622  123 4055 3886
  415 2929 3222 2021  162 2494 3370 4239 1804  805   61 3532 4344 4823
 1000 3342 3703 4641  561 4487 1737 1150 4224 1546 4446 

In [45]:
inicio = time.perf_counter()

res= func(get_elem_in_diag(degree_mat_from_adj(A,5000)),5000) 

final = time.perf_counter()

print("genes relevantes son",res )
print("el tiempo de corrida fue, ", final- inicio)

genes relevantes son [ 465 3742  365 ...  414 1910 2112]
el tiempo de corrida fue,  80.69214150000062


In [29]:
inicio = time.perf_counter()

M_6000=mat_shape(A,6000).dot(get_elem_in_diag( degree_mat_from_adj(A,6000)))
M_6000_2=np.squeeze(np.asarray(M_6000))
res= func(M_6000_2,6000)

final = time.perf_counter()

print("genes relevantes son",res )
print("el tiempo de corrida fue, ", final- inicio)

genes relevantes son [ 465 3742  365 5436 3766 3866 1631 3241 2457 3067 1540 3976 5971 3383
 4617 1467 4336  894 3692 1299 3779 4625 2032 1716 2285 2005 5630 3181
 4204 5576 4407   66 5563 1430 2517 2071 2096 4162 4230  514 4173  166
 1255 4709 3719 3741 4459   31 5763 5632 5593  263 4514 3384 2180  251
 2597  221 3975  555 4098 2077  358 1128 1488 2504 5566 4681 5817  806
 5366 4835 2568  214  918 4721 2985 1655 3743  811 4066 2370 4907 5978
 4009 1419 5623 3755 4221 3491  619 1302 1620 1924   43 1342 4399 1884
 4001 1885 5602 1363 4770 5733  649 5534 1409 4256 1839  565 3923  316
  732 3379 1521 3355 5232 2124  317 1935 1025 3343  718 3460 1376 4473
  557 4386 4055  127 5488 4485 1644 4243 2578 4022 1284 2838 1855 3993
 4014 1629 5255 3370 2182 2263 5914 3859 3323 5040 3186 5826  891 3592
 3977 3700 2871 3509 3815  162 3551 5511  373 2494 4097 3673 1835 1256
 1461 4823 5931  156 5074 1877 5970 3310 3222 2275 4771  892 1453  375
  561   41 3458  805 2161 5915 3235 3622 4446 5141 3348 

In [47]:
inicio = time.perf_counter()

res= func(get_elem_in_diag(degree_mat_from_adj(A,6000)),6000) 

final = time.perf_counter()

print("genes relevantes son",res )
print("el tiempo de corrida fue, ", final- inicio)

genes relevantes son [ 465 3742  365 ... 2112 5860 5143]
el tiempo de corrida fue,  113.08701519999977


In [30]:
inicio = time.perf_counter()

M_7000=mat_shape(A,7000).dot(get_elem_in_diag( degree_mat_from_adj(A,7000)))
M_7000_2=np.squeeze(np.asarray(M_7000))
res= func(M_7000_2,7000)

final = time.perf_counter()

print("genes relevantes son",res )
print("el tiempo de corrida fue, ", final- inicio)

MemoryError: 

In [49]:
inicio = time.perf_counter()

res= func(get_elem_in_diag(degree_mat_from_adj(A,7000)),7000) 

final = time.perf_counter()

print("genes relevantes son",res )
print("el tiempo de corrida fue, ", final- inicio)

genes relevantes son [ 465 3742  365 ... 5860 2112 5143]
el tiempo de corrida fue,  155.3664633999997


In [15]:
inicio = time.perf_counter()

M_8000=mat_shape(A,8000).dot(get_elem_in_diag( degree_mat_from_adj(A,8000)))
M_8000_2=np.squeeze(np.asarray(M_8000))
res= func(M_8000_2,8000)

final = time.perf_counter()

print("genes relevantes son",res )
print("el tiempo de corrida fue, ", final- inicio)

genes relevantes son [ 465 7948 3742 ... 2112 7635 5143]
el tiempo de corrida fue,  215.10149769999998


In [16]:
inicio = time.perf_counter()

res= func(get_elem_in_diag(degree_mat_from_adj(A,8000)),8000) 

final = time.perf_counter()

print("genes relevantes son",res )
print("el tiempo de corrida fue, ", final- inicio)

genes relevantes son [ 465 7948 3742 ... 2112 7635 5143]
el tiempo de corrida fue,  197.34504449999997


In [18]:
inicio = time.perf_counter()

M_9000=mat_shape(A,9000).dot(get_elem_in_diag( degree_mat_from_adj(A,9000)))
M_9000_2=np.squeeze(np.asarray(M_9000))
res= func(M_9000_2,9000)

final = time.perf_counter()

print("genes relevantes son",res )
print("el tiempo de corrida fue, ", final- inicio)

MemoryError: 